server:
  port: 8090
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  application:
    name: zuul-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
#不拦截token路径--相对路径
freeurl:
  list:
    - /user-server/login
    - /app-server/app/getApp2
zuul:
  routes:
    userapi:
      path: /user-server/**
      serviceId: user-server
    appapi:
      path: /app-server/**
      serviceId: app-server
