server:
  port: 9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
  dashboard: false
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  application:
    name: app-server
